// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy7Cggoe8zZWey7iACrB8y71kSEI_l2rk',
    appId: '1:1045863495888:web:45fc2b8748af318ee5c6d5',
    messagingSenderId: '1045863495888',
    projectId: 'flutter-auth-7bfa6',
    authDomain: 'flutter-auth-7bfa6.firebaseapp.com',
    storageBucket: 'flutter-auth-7bfa6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4nUixnnxHQIene9AbYn2yHj-XFVow08Y',
    appId: '1:1045863495888:android:dc5c49dc33e3c0c8e5c6d5',
    messagingSenderId: '1045863495888',
    projectId: 'flutter-auth-7bfa6',
    storageBucket: 'flutter-auth-7bfa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvqF-YR7GUTXnBPUy6FMGM9y-HfpSPBe4',
    appId: '1:1045863495888:ios:d015b61319b5c27be5c6d5',
    messagingSenderId: '1045863495888',
    projectId: 'flutter-auth-7bfa6',
    storageBucket: 'flutter-auth-7bfa6.appspot.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvqF-YR7GUTXnBPUy6FMGM9y-HfpSPBe4',
    appId: '1:1045863495888:ios:0ddc7bbd287c4c46e5c6d5',
    messagingSenderId: '1045863495888',
    projectId: 'flutter-auth-7bfa6',
    storageBucket: 'flutter-auth-7bfa6.appspot.com',
    iosBundleId: 'com.example.authApp.RunnerTests',
  );
}
